config/routes.rb
Rails.application.routes.draw do
  get 'jobs/:id/download_result_file' => 'jobs#download_result_file', as: :download_jobs_result_file

  get 'jobs/:id/schedule' => 'jobs#schedule', as: :schedule_job
  get 'jobs/:id/cancel' => 'jobs#cancel', as: :cancel_job

  resources :jobs

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  after_destroy :delete_work_dir

  mount_uploader :target_file_1, FastqUploader
  mount_uploader :target_file_2, FastqUploader

  has_one :job_queue

  validates_presence_of :tool
  validates_presence_of :target_file_1
  validates_presence_of :status

  STATUS = {'created' => I18n.t('messages.status.created'),
            'scheduled' => I18n.t('messages.status.scheduled'),
            'doing' => I18n.t('messages.status.doing'),
            'canceling' => I18n.t('messages.status.canceling'),
            'canceled' => I18n.t('messages.status.canceled'),
            'error' => I18n.t('messages.status.error'),
            'done' => I18n.t('messages.status.done')}

  def schedulable?
    self.status == 'created' || self.status == 'canceled'
  end

  def cancelable?
    self.status == 'scheduled' || self.status == 'doing'
  end

  def editable?
    self.status == 'created' || self.status == 'canceled' || self.status == 'error'
  end

  def deletable?
    !(self.status == 'scheduled' || self.status == 'doing' || self.status == 'canceling')
  end

  def schedule
    return false unless schedulable?

    Job.transaction do
      self.create_job_queue
      self.status = 'scheduled'
      self.started_at = nil
      self.finished_at = nil
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.schedule_job_failed'))
      logger.error(e.message)
      false
  end

  def be_doing
    Job.transaction do
      self.status = 'doing'
      self.started_at = Time.current
      self.finished_at = nil
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.doing_job_failed'))
      logger.error(e.message)
      false
  end

  def cancel
    return false unless cancelable?

    Job.transaction do
      self.status = 'canceling'
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.canceling_job_failed'))
      logger.error(e.message)
      false
  end

  def be_canceled
    Job.transaction do
      self.job_queue.try(:destroy!)
      self.job_queue = nil
      self.status = 'canceled'
      self.finished_at = Time.current
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.cancel_job_failed'))
      logger.error(e.message)
      false
  end

  def be_done
    Job.transaction do
      self.job_queue.try(:destroy!)
      self.job_queue = nil
      self.status = 'done'
      self.finished_at = Time.current
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.done_job_failed'))
      logger.error(e.message)
      false
  end

  def error_occurred
    Job.transaction do
      self.job_queue.try(:destroy!)
      self.job_queue = nil
      self.status = 'error'
      self.finished_at = Time.current
      self.save!
    end
      true
    rescue => e
      logger.error(I18n.t('messages.error_occurred_job_failed'))
      logger.error(e.message)
      false
  end

  def update_with_status( params )
    if self.update params
      self.status = 'created'
      self.save!
    end
  end

  def command
    self.send "#{self.tool}_command" if self.tool.present?
  end

  def script
    return nil if command.blank?

    script_path = "#{work_path}/job_command_#{self.id}.sh"

    File.open(script_path, "w", 0755) do |f|
      f.write command
    end

    # execute background and return pid
    "#{script_path} > #{work_path}/job_command_#{self.id}.log 2>&1 & echo $!"
  end

  def done?
    pid = self.job_queue.try(:command_pid)
    return true unless pid

    begin
      return false if `ps #{pid}` =~ /#{pid}/
    rescue => e
      Rails.logger.error e.message
    end
    true
  end

  def result_files
    files = Dir.glob("#{Rails.root}/#{work_path}/*")
    files.select{|f| !(f =~ /job_command_[\d]+.sh/)}.map{|f| File.basename f}
  end

  def result_file(file_name)
    "#{Rails.root}/#{work_path}/#{file_name}"
  end

  private

  def vicuna_command
    create_work_dir
    config_base_file = "#{Rails.root}/config/vicuna_config.txt"
    config_file = "#{work_path}/job_#{self.id}_#{tool}_config.txt"
    tool_log = "#{work_path}/job_#{self.id}_#{tool}.log"

    File.open(config_file, "w", 0644) do |f_out|
      File.open(config_base_file, "r") do |f_in|
        f_in.each_line do |line|
          replaced_line = line.gsub(/\#\{input_directory\}/, "#{Rails.root}/#{work_path}/")
          replaced_line = replaced_line.gsub(/\#\{output_directory\}/, "#{Rails.root}/#{work_path}/")
          f_out.write replaced_line
        end
      end
    end

    return nil unless FileTest.exist?(config_file)
    FileUtils.ln_sf(self.target_file_1.path, "#{work_path}/#{self.target_file_1.file.filename}")
    FileUtils.ln_sf(self.target_file_2.path, "#{work_path}/#{self.target_file_2.file.filename}")

    command_string = <<-"EOS"
    OMP_NUM_THREADS=#{Settings.cpu_core_count} vicuna-omp-v1.0 #{config_file} > #{tool_log} 2>&1;
    EOS

    command_string
  end

  def bwa_command
    logger.error "bwa command is not supported now"
    return nil
=begin
    basename_1 = File.basename(self.target_file_1.path, File.extname(self.target_file_1.path))
    basename_2 = File.basename(self.target_file_2.path, File.extname(self.target_file_1.path))
    sai_1_path = "tmp/job_work/#{self.id}/#{basename_1}.sai"
    sai_2_path = "tmp/job_work/#{self.id}/#{basename_2}.sai"
    sam_path = "tmp/job_work/#{self.id}/#{basename_1}.sam"
    cmp_path = "tmp/job_work/#{self.id}/cmp"

    command = <<-"EOS"
    bwa index -a bwtsw #{self.reference_file_1.path}
    bwa aln -t 2 #{self.reference_file_1.path} #{self.target_file_1.path} > #{sai_1_path}
    bwa aln -t 2 #{self.reference_file_1.path} #{self.target_file_2.path} > #{sai_2_path}
    bwa sampe -P #{self.reference_file_1.path} #{sai_1_path} #{sai_2_path} #{self.target_file_1.path} #{self.target_file_2.path} -r "@RG\tID:01\tSM:s6\tPL:Illumina" > #{sam_path}
    touch #{cmp_path}
    EOS
    command
=end
  end

  def bwa2_command
    logger.error "bwa2 command is not supported now"
    nil
  end

  def sam_tools_command
    logger.error "sam_tools command is not supported now"
    return nil
=begin
    basename_1 = File.basename(self.target_file_1.path, File.extname(self.target_file_1.path))
    sam_path = "tmp/job_work/#{self.id}/#{basename_1}.sam"
    bam_path = "tmp/job_work/#{self.id}/#{basename_1}.bam"
    sorted_name = "tmp/job_work/#{self.id}/#{basename_1}_sorted"
    sorted_bam_path = "#{sorted_name}.bam"
    cmp_path = "tmp/job_work/#{self.id}/cmp"

    command = <<-"EOS"
    samtools view -bS #{sam_path} > #{bam_path}
    samtools sort #{bam_path} #{sorted_name}
    samtools index #{sorted_bam_path}
    touch #{cmp_path}
    EOS
    command
=end
  end

  def bowtie_command
    logger.error "bowtie command is not supported now"
    nil
  end

  def bowtie2_command
    create_work_dir
    index_file = "#{indexes_path}#{self.reference_genome}"
    tool_log = "#{work_path}/job_#{self.id}_#{tool}.log"
    un_conc_result = "#{work_path}/job_#{self.id}_un.fastq"
    al_conc_result = "#{work_path}/job_#{self.id}_al.fastq"
    un_conc_result_1 = "#{work_path}/job_#{self.id}_un.1.fastq"
    un_conc_result_2 = "#{work_path}/job_#{self.id}_un.2.fastq"
    al_conc_result_1 = "#{work_path}/job_#{self.id}_al.1.fastq"
    al_conc_result_2 = "#{work_path}/job_#{self.id}_al.2.fastq"
    un_conc_trimmed_result_1 = "#{work_path}/job_#{self.id}_un_trim_1.fastq"
    un_conc_trimmed_result_2 = "#{work_path}/job_#{self.id}_un_trim_2.fastq"
    al_conc_trimmed_result_1 = "#{work_path}/job_#{self.id}_al_trim_1.fastq"
    al_conc_trimmed_result_2 = "#{work_path}/job_#{self.id}_al_trim_2.fastq"

    command_string = <<-"EOS"
    bowtie2 -p #{Settings.cpu_core_count} --un-conc #{un_conc_result} --al-conc #{al_conc_result} -x #{index_file} -1 #{self.target_file_1.path} -2 #{self.target_file_2.path} 1>/dev/null 2>#{tool_log};
    fastq_quality_filter -Q33 -q 20 -p 80 -i #{un_conc_result_1} | fastq_quality_trimmer -Q33 -t 20 -l 10 -o #{un_conc_trimmed_result_1};
    fastq_quality_filter -Q33 -q 20 -p 80 -i #{un_conc_result_2} | fastq_quality_trimmer -Q33 -t 20 -l 10 -o #{un_conc_trimmed_result_2};
    fastq_quality_filter -Q33 -q 20 -p 80 -i #{al_conc_result_1} | fastq_quality_trimmer -Q33 -t 20 -l 10 -o #{al_conc_trimmed_result_1};
    fastq_quality_filter -Q33 -q 20 -p 80 -i #{al_conc_result_2} | fastq_quality_trimmer -Q33 -t 20 -l 10 -o #{al_conc_trimmed_result_2};
    EOS

    command_string
  end

  def work_path
    "#{Settings.job.work_path}/#{self.id}"
  end

  def cmp_path
    "#{work_path}/cmp"
  end

  def create_work_dir
    FileUtils.mkdir_p(work_path) unless FileTest.exist?(work_path)
  end

  def delete_work_dir
    FileUtils.rm_rf(work_path) if FileTest.exist?(work_path)
  end

  def indexes_path
    "#{Settings.job.indexes_path}/"
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :schedule, :cancel, :download_result_file]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # GET /jobs/1/schedule
  def schedule
    respond_to do |format|
      if @job.schedule
        format.html { redirect_to jobs_url, notice: t('messages.scheduled_job') }
      else
        format.html { redirect_to jobs_url, alert: t('messages.schedule_job_failed') }
      end
    end
  end

  # GET /jobs/1/cancel
  def cancel
    respond_to do |format|
      if @job.cancel
        format.html { redirect_to jobs_url, notice: t('messages.canceled_job') }
      else
        format.html { redirect_to jobs_url, alert: t('messages.cancel_job_failed') }
      end
    end
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: t('messages.created_job') }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update_with_status(job_params)
        format.html { redirect_to @job, notice: t('messages.updated_job') }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: t('messages.deleted_job') }
      format.json { head :no_content }
    end
  end

  # GET /jobs/1/download_result_file
  def download_result_file
    render show_job_path(params[:id]) and return if params[:file_name].blank?
    send_file @job.result_file(params[:file_name])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:tool, :comment,
                                  :target_file_1, :target_file_1_cache, :remove_target_file_1,
                                  :target_file_2, :target_file_2_cache, :remove_target_file_2,
                                  :reference_genome)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
  def schedulable( job )
    job.schedulable?
  end

  def cancelable( job )
    job.cancelable?
  end

  def editable( job )
    job.editable?
  end

  def deletable( job )
    job.deletable?
  end
end

app/views/jobs/_form.html.slim
= form_for(@job) do |f|
  - if @job.errors.any?
    #error_explanation
      .alert.alert-danger
        h2
          = pluralize(@job.errors.count, "error")
        ul
          - @job.errors.full_messages.each do |message|
            li
              = message
  - unless controller.action_name == 'new'
  .row.form-group
    .col-md-2
      = f.label :id
      br
    .col-md-2
      = @job.id
  .row.form-group
    .col-md-2
      = f.label :tool
      | *
      br
    .col-md-2
      = f.select :tool, tool_labels, {}, class: 'form-control', onchange: "update_reference_genome()"
  .row.form-group
    .col-md-2
      = f.label :target_file_1
      | *
      br
    .col-md-4
      = f.file_field :target_file_1, class: 'filestyle form-control'
      = f.hidden_field :target_file_1_cache
    - if @job.target_file_1?
      .checkbox.col-md-2
        = f.check_box :remove_target_file_1
        = t('messages.delete_file')
  .row.form-group
    .col-md-2
      = f.label :target_file_2
      br
    .col-md-4
      = f.file_field :target_file_2, class: 'filestyle form-control'
      = f.hidden_field :target_file_2_cache
    - if @job.target_file_2?
      .checkbox.col-md-2
        = f.check_box :remove_target_file_2
        = t('messages.delete_file')
  #reference_genome.row.form-group
    .col-md-2
      = f.label :reference_genome
      | *
      br
    .col-md-2
      = f.select :reference_genome, reference_genome_labels, {include_blank: true}, {class: 'form-control'}
  .row.form-group
    .col-md-2
      = f.label :comment
      br
    .col-md-4
      = f.text_field :comment, class: 'form-control'
  - unless controller.action_name == 'new'
  .row.form-group
    .col-md-2
      = f.label :status
      br
    .col-md-2
      =  Job::STATUS[@job.status]
  .row.form-group
    .col-md-2
      = f.submit class: "btn btn-primary", data: {disable_with: t('messages.creating_or_updating')}
br

app/views/jobs/edit.html.slim
h1
  | Editing Job
= render 'form'
.row
  .col-md-1
    = link_to t('messages.show'), @job, class: "btn btn-default"
  .col-md-1
    = link_to t('messages.back'), jobs_path, class: "btn btn-default"

app/views/jobs/index.html.slim
h1
  | Listing jobs
br
table.table.table-striped
  thead
    tr
      th
        = t('activerecord.attributes.job.id')
      th
        = t('activerecord.attributes.job.tool')
      th
        = t('activerecord.attributes.job.target_file_1')
      th
        = t('activerecord.attributes.job.target_file_2')
      th
        = t('activerecord.attributes.job.reference_genome')
      th
        = t('activerecord.attributes.job.comment')
      th
        = t('activerecord.attributes.job.status')
      th
        = t('activerecord.attributes.job.started_at')
      th
        = t('activerecord.attributes.job.finished_at')
      th[colspan="4"]
        = t('messages.action')
  tbody
    - @jobs.each do |job|
      tr
        td
          = job.id
        td
          = job.tool
        td
          = job.target_file_1.file.try(:filename) if job.target_file_1
        td
          = job.target_file_2.file.try(:filename) if job.target_file_2
        td
          = job.reference_genome
        td
          = job.comment
        td
          = Job::STATUS[job.status]
        td
          = job.started_at.strftime('%Y/%m/%d %H:%M') if job.started_at
        td
          = job.finished_at.strftime('%Y/%m/%d %H:%M') if job.finished_at
        td
          = link_to t('messages.schedule'), schedule_job_path(job) if schedulable job
          = link_to t('messages.cancel'), cancel_job_path(job) if cancelable job
        td
          = link_to t('messages.show'), job
        td
          = link_to t('messages.edit'), edit_job_path(job) if editable job
        td
          = link_to t('messages.delete'), job, method: :delete, data: { confirm: 'Are you sure?' } if deletable job
br
.row
  .col-md-1
    = link_to t('messages.new_job'), new_job_path, class: "btn btn-primary"

app/views/jobs/new.html.slim
h1
  | New Job
= render 'form'
.row
  .col-md-1
    = link_to t('messages.back'), jobs_path, class: "btn btn-default"

app/views/jobs/show.html.slim
h1
  | Job Detail
.row
  .col-md-2
    = t('activerecord.attributes.job.id')
  .col-md-2
    = @job.id
br
.row
  .col-md-2
    = t('activerecord.attributes.job.tool')
  .col-md-2
    = @job.tool
br
.row
  .col-md-2
    = t('activerecord.attributes.job.target_file_1')
  .col-md-4
    = @job.target_file_1.file.try(:filename) if @job.target_file_1
br
.row
  .col-md-2
    = t('activerecord.attributes.job.target_file_2')
  .col-md-4
    = @job.target_file_2.file.try(:filename) if @job.target_file_2
br
.row
  .col-md-2
    = t('activerecord.attributes.job.reference_genome')
  .col-md-2
    = @job.reference_genome
br
.row
  .col-md-2
    = t('activerecord.attributes.job.comment')
  .col-md-4
    = @job.comment
br
.row
  .col-md-2
    = t('activerecord.attributes.job.results')
- (@job.result_files.presence || []).each_with_index do |file, i|
  .row
    .col-md-2

    .col-md-4
      = link_to file, download_jobs_result_file_path(file_name: file)
br
.row
  .col-md-2
    = t('activerecord.attributes.job.status')
  .col-md-2
    = Job::STATUS[@job.status]
br
.row
  .col-md-2
    = t('activerecord.attributes.job.started_at')
  .col-md-2
    = @job.started_at.strftime('%Y/%m/%d %H:%M') if @job.started_at
br
.row
  .col-md-2
    = t('activerecord.attributes.job.finished_at')
  .col-md-2
    = @job.finished_at.strftime('%Y/%m/%d %H:%M') if @job.finished_at
br
.row
  .col-md-1
    = link_to t('messages.edit'), edit_job_path(@job), class: "btn btn-default"
  .col-md-1
    = link_to t('messages.back'), jobs_path, class: "btn btn-default"